name: Laba_2.14
channels:
  - defaults
dependencies:
  - blas=1.0=mkl
  - bottleneck=1.3.5=py311h5bb9823_0
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2023.08.22=haa95532_0
  - icc_rt=2022.1.0=h6049295_2
  - intel-openmp=2023.1.0=h59b6b97_46319
  - libffi=3.4.4=hd77b12b_0
  - mkl=2023.1.0=h6b88ed4_46357
  - mkl-service=2.4.0=py311h2bbff1b_1
  - mkl_fft=1.3.6=py311hf62ec03_1
  - mkl_random=1.2.2=py311hf62ec03_1
  - numexpr=2.8.4=py311h1fcbade_1
  - numpy=1.25.2=py311hdab7c0b_0
  - numpy-base=1.25.2=py311hd01c5d8_0
  - openssl=3.0.10=h2bbff1b_2
  - pandas=2.0.3=py311hf62ec03_0
  - pip=23.2.1=py311haa95532_0
  - python=3.11.4=he1021f5_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - pytz=2022.7=py311haa95532_0
  - scipy=1.11.1=py311hc1ccb85_0
  - setuptools=68.0.0=py311haa95532_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.2=h2bbff1b_0
  - tbb=2021.8.0=h59b6b97_0
  - tk=8.6.12=h2bbff1b_0
  - tzdata=2023c=h04d1e81_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.38.4=py311haa95532_0
  - xz=5.4.2=h8cc25b3_0
  - zlib=1.2.13=h8cc25b3_0
  - pip:
    - absl-py==1.4.0
    - astunparse==1.6.3
    - cachetools==5.3.1
    - certifi==2023.7.22
    - charset-normalizer==3.2.0
    - flatbuffers==23.5.26
    - gast==0.4.0
    - google-auth==2.22.0
    - google-auth-oauthlib==1.0.0
    - google-pasta==0.2.0
    - grpcio==1.57.0
    - h5py==3.9.0
    - idna==3.4
    - keras==2.13.1
    - libclang==16.0.6
    - markdown==3.4.4
    - markupsafe==2.1.3
    - numpy==1.24.3
    - oauthlib==3.2.2
    - opt-einsum==3.3.0
    - packaging==23.1
    - protobuf==4.24.2
    - pyasn1==0.5.0
    - pyasn1-modules==0.3.0
    - requests==2.31.0
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - tensorboard==2.13.0
    - tensorboard-data-server==0.7.1
    - tensorflow==2.13.0
    - tensorflow-estimator==2.13.0
    - tensorflow-intel==2.13.0
    - tensorflow-io-gcs-filesystem==0.31.0
    - termcolor==2.3.0
    - typing-extensions==4.5.0
    - urllib3==1.26.16
    - werkzeug==2.3.7
    - wrapt==1.15.0
prefix: C:\Users\Gaming-PC\.conda\envs\Laba_2.14
